# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34055f7a3d6e57d675be2028cb8a711f8feb921e434d7dbda689bd696baf8dabc69fc17cfaa90782ce06fce40b008c7d87d6d1171c6d39f726e6124d6d79e50d

test:
  secret_key_base: e4436c0bae4a1c173d1b1ae5bc0247322fcf492961a646a93a06eb3a8aed64fa5a5c934f31303783956d7a96d1d5ef370c1bebd44a8f2f7ef3f1895eba9c2837

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
